# <center>Osnove vanilla Python-a</center>

<center>
  <a href="https://www.python.org/"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/800px-Python-logo-notext.svg.png" alt="Pyhton" width="64" height="64"/><a/>
</center>


### 1. Ispis

In [ ]:
print(1)

1


In [ ]:
print(1 + 1)

2


In [ ]:
print("Hello world")

Hello world


In [ ]:
print("Hello wolrd", end=" ")
print("Hello world")

Hello wolrdHello world


In [ ]:
print("1" + "1")

11


In [ ]:
print(2 + 3j)

(2+3j)


In [ ]:
print(1, 2, "3")

1 2 3


In [ ]:
print(1 + "1")

TypeError: ignored

In [ ]:
Print("print")

NameError: ignored

In [ ]:
# Google notebook
1 + 2

3

### 2. Operacije

In [ ]:
print(9 + 5)
print(9 - 5)
print(9 * 5)
print(9 / 5)

14
4
45
1.8


In [ ]:
print(10 / 3)

3.3333333333333335


In [ ]:
print(9 ** 5)
print(9 // 5)

59049
1


In [ ]:
print(9 *** 5)

SyntaxError: ignored

In [ ]:
print(9 % 5)

4


In [ ]:
print(9 & 5)
print(9 | 5)
print(9 ^ 5)
print(~5)
print(9 << 2)
print(9 >> 2)

1
13
12
-6
36
2


In [ ]:
print(2 + 3 * 4 / (5 - 6))

-10.0


### 3. Varijable

In [ ]:
my_var = 10
print(my_var)

10


In [ ]:
my_var1 = 11
print(my_var1)

11


In [ ]:
1my_var = 12
print(1my_var)

SyntaxError: ignored

In [ ]:
my var = 13
print(my var)

SyntaxError: ignored

In [ ]:
myVar = 14
print(myVar)

14


In [ ]:
a = 1
b = 2
print(a + b)

3


In [ ]:
a = 1
print(a + 2)

3


In [ ]:
a = 1
a = a + 5
print(a)

6


In [ ]:
a = 10
b = 20

print(a, b)

temp = a
a = b
b = temp

print(a, b)

10 20
20 10


In [ ]:
a = 10
a += 5
print(a)

a += a
print(a)

a *= 2
print(a)

15
30
60


In [ ]:
print(True)
print(False)

print(3 > 2)
print(2 == 2)

print(not True)
print(2 != 3)
print(2 >= 3)
print(10 + 20 > 15)

True
False
True
True
False
True
False
True


### 4. Uvijeti

In [ ]:
if 1 + 1 == 2:
    print("Hello 1")

Hello 1


In [ ]:
if 1 + 1 == 2:
    print("Hello 2")

    if 1 + 1 == 3:
        print("Hello 3")

Hello 2


In [ ]:
if 1 + 1 == 3:
    print("Hello 4")

    if 1 + 1 == 2:
        print("Hello 5")

In [ ]:
if True:
    print("Hi")

Hi


In [ ]:
if True and False:
    print("Hi")

In [ ]:
a = True
b = False
c = True

if a or b or c:
    print("Hi")

Hi


In [ ]:
a = input("a:")

if a == "3":
    print("Tri")
elif a == "4":
    print("Četiri")
else:
    print("Krivi unos broja!")

a:4
Četiri


In [ ]:
if True == False:
    print(True)

In [ ]:
a = 10

if a > 5:
    print("Hi 1")
elif a > 8:
    print("Hi 2")
elif a > 10:
    print("Hi 3")
else:
    print("Else")

Hi 1


### 5. For petlje

In [ ]:
for i in range(10):
    print("Hi")

Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi


In [ ]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(5, 10):
    print(i)

5
6
7
8
9


In [ ]:
for i in range(5):
    print(i)

0
1
2
3
4


In [ ]:
for i in range(5):
    print(i + 10)

10
11
12
13
14


In [ ]:
for i in range(5):
    print(i > 3)

False
False
False
False
True


In [ ]:
for i in range(10):
    if i % 2 == 0:
        print(i, "je parni broj")

0 je parni broj
2 je parni broj
4 je parni broj
6 je parni broj
8 je parni broj


In [ ]:
for broj in range(10):
    print(broj)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(5):
    for j in range(5):
        print(i, j)

0 0
0 1
0 2
0 3
0 4
1 0
1 1
1 2
1 3
1 4
2 0
2 1
2 2
2 3
2 4
3 0
3 1
3 2
3 3
3 4
4 0
4 1
4 2
4 3
4 4


In [ ]:
count = 0
for i in range(100):
    if i < 10:
        count += 1

print(count)

10


In [ ]:
for i in range(100):
    if i < 5:
        continue

    if i > 10:
        break

    print(i)

5
6
7
8
9
10


In [ ]:
for i in range(2, 20):
    prost = True
    for j in range(2, i):
        if i % j == 0:
            prost = False
            break

    if prost:
        print(i, "je prost")

2 je prost
3 je prost
5 je prost
7 je prost
11 je prost
13 je prost
17 je prost
19 je prost


### 6. Built-in funkcije

In [ ]:
print("hello")

hello


In [ ]:
len("hello")

5

In [ ]:
int("23")

23

In [ ]:
min(3, 5)

3

In [ ]:
type(4.3)

float

In [ ]:
type("1" + "String")

str

In [ ]:
help()


Welcome to Python 3.10's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the internet at https://docs.python.org/3.10/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".

help> 

You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.


### 7. Polja (arrays)

In [ ]:
a = [1, 2, 3]
print(a)

[1, 2, 3]


In [ ]:
a = []
print(a)

[]


In [ ]:
a = [1, 2, 3]
b = [4, 5, 6]
print(a + b)

[1, 2, 3, 4, 5, 6]


In [ ]:
a = [1, 2, 3]
b = [4, 5, 6]
print(a - b)

TypeError: ignored

In [ ]:
a = [1, 2, 3]
a.append(4)
print(a)

[1, 2, 3, 4]


In [ ]:
len([1, 2, 3])

3

In [ ]:
a = [1, 2, 3, 4]
print(a[0])
print(a[2])
print(a[-1])
print(a[:1])
print(a[3:1:-1])

1
3
4
[1]
[4, 3]


In [ ]:
a = []
a.append(1)
a.append(2)
a.remove(1)
a.append(3)
print(a)

a.append(len(a))
a.index(3)
a.pop(0)
a.pop(a.index(3))
print(a)

[2, 3]
[2]


In [ ]:
a = [1, 2, 3, 6]
for i in range(len(a)):
    print(a[i])

1
2
3
6


In [ ]:
a = [1, 2, 3, 4]
for i in range(len(a)):
    print(a[i + 1])

2
3
4


IndexError: ignored

In [ ]:
numbers = [1, 2, 3]
for num in numbers:
    print(num)

1
2
3


In [ ]:
numbers = [1, 2, 3, 4]
numbers_reverse = []

for i in range(len(numbers)):
    num = numbers[len(numbers) - i - 1]
    numbers_reverse.append(num)

print(numbers_reverse)

[4, 3, 2, 1]


In [ ]:
numbers = [1, 2, 3, 4]
numbers_reverse = []
n = len(numbers)

for i in range(n):
    num = numbers[n - i - 1]
    numbers_reverse.append(num)

print(numbers_reverse)

[4, 3, 2, 1]


In [ ]:
numbers = [1, 2, 3, 4]
numbers_reverse = []
n = len(numbers)

for i in range(n):
    num = numbers[-i - 1]
    numbers_reverse.append(num)

print(numbers_reverse)

[4, 3, 2, 1]


In [ ]:
numbers = [1, 2, 3, 4]
numbers_reverse = numbers[::-1]

print(numbers_reverse)

[4, 3, 2, 1]


In [ ]:
numbers = [1, 2, 3, 4]
numbers.reverse()

print(numbers)

[4, 3, 2, 1]


In [ ]:
numbers = [1, 2, 3, 4]
numbers_reverse = list(reversed(numbers))

print(numbers_reverse)

[4, 3, 2, 1]


In [ ]:
a = [1, 4, 2, 3, 0]
a.sort()
print(a)

[0, 1, 2, 3, 4]


### 8. Funkcije

In [ ]:
def my_function():
    print("Hi")

my_function()

Hi


In [ ]:
def my_function(number):
    print(number)

my_function(123)
my_function("abc")

123
abc


In [ ]:
def a():
    print("Hi")

def b():
    a()

b()

Hi


In [ ]:
def plus_one(n):
    return n + 1

print(plus_one(3))

4


In [ ]:
def add(a, b):
    return a + b

print(add(3, 4))

7


In [ ]:
def print_name(name="John"):
    print(name)


print_name("Mark")
print_name()

Mark
John


### Zadatak

In [ ]:
# Napravi polje u kojem ćeš upisati marke auta, a onda ako naziv manji od 3 slova,
# izbaci ga iz polja. Nakon toga dodaj jednu marku u sredinu liste.

### 9. Standard library Paketi (math, time, random)

Poznati su još: os, sys, datetime, collections, json, re, csv, itertools...

In [ ]:
import math

print(math.sqrt(25))
print(math.pi)
print(math.factorial(5))
print(math.sin(math.radians(30)))

5.0
3.141592653589793
120
0.49999999999999994


In [ ]:
import time

current_timestamp = time.time()
print(current_timestamp)

current_time = time.ctime(current_timestamp)
print(current_time)

print("Hello", end=" ")
time.sleep(2)
print("World")

start_time = time.time()
time.sleep(2)
end_time = time.time()
execution_time = end_time - start_time
print(f"Vrijeme izvršavanja {execution_time}")

1698095949.5624247
Mon Oct 23 21:19:09 2023
Hello World
Vrijeme izvršavanja 2.002469301223755


In [ ]:
import random

print(random.randint(1, 100))
print(random.random())

arr = ["Jabuka", "Banana", "Trešnja", "Jagoda"]
print(random.choice(arr))

random.shuffle(arr)
print(arr)

20
0.7377083887030682
Jagoda
['Banana', 'Trešnja', 'Jabuka', 'Jagoda']


# <center> Osnove NumPy paketa </center>
<center>
  <a href="https://numpy.org/"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/1200px-NumPy_logo_2020.svg.png" alt="NumPy" width="128" height="64"/></a>
</center>

In [ ]:
import numpy as np

In [ ]:
# Array
arr = np.array([
    [1, 2, 3, 4, 5, 6, 7],
    [8, 9, 10, 11, 12, 13, 14],
])

arr

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
# 2D array (matrica)
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.std(arr))

21
1
6
3.5
1.707825127659933


In [ ]:
np.random.rand()

0.3369361202357404

In [ ]:
np.random.rand(3, 2)

array([[0.02672882, 0.5976605 ],
       [0.78925908, 0.38568641],
       [0.15526165, 0.17063079]])

In [ ]:
np.random.randint(1, 100, 5)

array([32, 22, 20, 14, 45])

In [ ]:
print(arr.shape)
print(arr.dtype)

(2, 7)
int64


In [ ]:
# Operacije nad cijelim nizem
print(arr + 2)
print(arr * 3)
print(arr ** 2)

[[ 3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16]]
[[ 3  6  9 12 15 18 21]
 [24 27 30 33 36 39 42]]
[[  1   4   9  16  25  36  49]
 [ 64  81 100 121 144 169 196]]


In [ ]:
# Dot product (skalarni umnožaka)
weights = np.random.rand(4)
bias = 2

print(np.dot(bias, weights))


#               [4]
# [1, 2, 3] dot [5] = 1*4 + 2*5 + 3*6 = 32
#               [6]
a = np.array([1, 2, 3])
b = np.array([4, 5, 6]).transpose()
print(np.dot(a, b))

a = np.random.rand(3)
b = np.random.rand(3).transpose()
print(np.dot(a, b))

[0.65841735 0.39929307 1.79543197 0.80764437]
32
0.46047677270846127


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr[2])
print(arr[1:4])

3
[2 3 4]


In [ ]:
np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3).T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3).transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.concatenate(([1, 2, 3], [4, 5, 6]), axis=0)

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr > 3)

[False False False  True  True  True  True  True  True]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[arr > 3])
print(arr[arr % 2 == 0])

[4 5 6 7 8 9]
[2 4 6 8]


In [ ]:
def is_small_prime(x):
    return x in [2, 3, 5, 7, 9, 11, 13, 17, 19]

arr = np.arange(1, 20)
print(arr)

prime_mask = list(map(is_small_prime, arr))
print(arr[prime_mask])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 2  3  5  7  9 11 13 17 19]


In [ ]:
np.random.rand(4, 3, 2)

array([[[0.71784718, 0.28290206],
        [0.9905607 , 0.94593784],
        [0.81379042, 0.23338365]],

       [[0.48561256, 0.49437343],
        [0.83981936, 0.03989975],
        [0.85083616, 0.15278095]],

       [[0.73276854, 0.17511006],
        [0.64138487, 0.77882445],
        [0.74505067, 0.89171305]],

       [[0.82155596, 0.43324236],
        [0.7819424 , 0.40099252],
        [0.88133923, 0.53504111]]])

### Zadatak

In [ ]:
# Treba napraviti 3 niza random integera od 1 do 10, spojiti te nizove u jedan veliki niz,
# maknuti duplikate i izbaciti minimalnu i maximalnu vrijednost iz niza.
# Nakon toga napraviti kopiju tog niza, te ispisati korijen svakog broja u nizu

# <center> Osnove Pandas paketa </center>
<center>
  <a href="https://pandas.pydata.org/"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Pandas_logo.svg/2560px-Pandas_logo.svg.png" alt="Pandas" width="128" height="64"/></a>
</center>




In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('grades.csv')
df

student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23

In [ ]:
df.head(5)

student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65

In [ ]:
df.tail(5)

student  language  science  maths  history
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23

In [ ]:
df.columns

Index(['student', 'language', 'science', 'maths', 'history'], dtype='object')

In [ ]:
print(df.student)
print()

print(df['student'])
print()

print('--Vise stupaca--')
print(df[['student','science']])

0     kumar
1     kevin
2     sammy
3    janice
4     peter
5      prem
6    carrol
Name: student, dtype: object

0     kumar
1     kevin
2     sammy
3    janice
4     peter
5      prem
6    carrol
Name: student, dtype: object

--Vise stupaca--
  student  science
0   kumar       56
1   kevin       34
2   sammy       23
3  janice       67
4   peter       56
5    prem       45
6  carrol       90


In [ ]:
df.iloc[1:4]

student  language  science  maths  history
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45

In [ ]:
for index, row in df.iterrows():
    print(index, row['student'])

0 kumar
1 kevin
2 sammy
3 janice
4 peter
5 prem
6 carrol


In [ ]:
df.iloc[3, 2]

67

In [ ]:
df.loc[df['language'] == 90]

student  language  science  maths  history
0   kumar        90       56     34       34
2   sammy        90       23     12       32
5    prem        90       45     45       34

In [ ]:
df.shape

(7, 5)

In [ ]:
df.size

35

In [ ]:
df.values

array([['kumar', 90, 56, 34, 34],
       ['kevin', 10, 34, 32, 67],
       ['sammy', 90, 23, 12, 32],
       ['janice', 20, 67, 90, 45],
       ['peter', 30, 56, 45, 65],
       ['prem', 90, 45, 45, 34],
       ['carrol', 50, 90, 45, 23]], dtype=object)

In [ ]:
df.dtypes

student     object
language     int64
science      int64
maths        int64
history      int64
dtype: object

### Zadatak

In [ ]:
# Koristeći grades.csv podatke dodati novi stupac ocjena koja ocjenjuje studenta po bodovima iz "language" stupca
#  0 - 49 bodova, ocjena 1
# 50 - 59 bodova, ocjena 2
# 60 - 74 bodova, ocjena 3
# 75 - 89 bodova, ocjena 4
# 90 - 100 bodova, ocjena 5